remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
   syntax_highlighter_opts:
      disable : true

theme: jekyll-theme-slate
